//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkShale.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser
    {
        public long Id { get; set; }
        public System.Guid UserId { get; set; }
        public string SessionId { get; set; }
        public bool IsLogin { get; set; }
        public string PageName { get; set; }
        public Nullable<System.DateTime> LastActivityOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
