//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkShale.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilkSaleDBEntities : DbContext
    {
        public MilkSaleDBEntities()
            : base("name=MilkSaleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginUser> LoginUsers { get; set; }
        public virtual DbSet<PasswordResetLinkForUser> PasswordResetLinkForUsers { get; set; }
        public virtual DbSet<TimeZoneList> TimeZoneLists { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserModulePermission> UserModulePermissions { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UserSubscription> UserSubscriptions { get; set; }
    }
}
