//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkShale.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZoneList
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string current_utc_offset { get; set; }
        public bool is_currently_dst { get; set; }
        public string ZoneId { get; set; }
    }
}
