//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkShale.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubscription
    {
        public System.Guid UserSubscriptionId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime PlanStartDate { get; set; }
        public Nullable<System.DateTime> PlanEndDate { get; set; }
        public Nullable<int> PlanDurationType { get; set; }
        public string PlanTypeName { get; set; }
        public System.Guid PlanReferenceId { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreateadOn { get; set; }
        public Nullable<int> PlanDuration { get; set; }
        public string PlanName { get; set; }
    
        public virtual User User { get; set; }
    }
}
